### ISSUE TITLE
Forms Plugin

### ISSUE THREAD

**Issue by JohnCampionJr** [windicss/vite-plugin-windicss#21]
Is the forms plugin working with `vite-plugin-windicss`?

I'm adding it to the tailwind.config

```
  plugins: [
    require('windicss/plugin/forms'),
    // ...
  ],
```

But the styles aren't coming through....

**Comment by JohnCampionJr** [comment]
I've figured out that the styles are being imported, but they seem to be overridden somewhere along the way.  I don't know if this is a bug in windicss or Vite-plugin-windicss

This is coming from the plugin
```css
input {
    -webkit-writing-mode: horizontal-tb !important;
    text-rendering: auto;
    color: -internal-light-dark(black, white);
    letter-spacing: normal;
    word-spacing: normal;
    text-transform: none;
    text-indent: 0px;
    text-shadow: none;
    display: inline-block;
    text-align: start;
    appearance: textfield;
    background-color: -internal-light-dark(rgb(255, 255, 255), rgb(59, 59, 59));
    -webkit-rtl-ordering: logical;
    cursor: text;
    margin: 0em;
    font: 400 13.3333px Arial;
    padding: 1px 2px;
    border-width: 2px;
    border-style: inset;
    border-color: -internal-light-dark(rgb(118, 118, 118), rgb(133, 133, 133));
    border-image: initial;
}

But its being overridden by this
```css
*, ::before, ::after {
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    border-width: 0;
    border-style: solid;
    border-color: #e5e7eb;
}
```

Is the forms plugin being imported too early perhaps?

**Comment by JohnCampionJr** [comment]
Test repo here
https://github.com/JohnCampionJr/vitesse/tree/bug/windicss-forms

**Comment by antfu** [comment]
@JohnCampionJr Which one comes first in your css?

**Comment by JohnCampionJr** [comment]
> @JohnCampionJr Which one comes first in your css?

I'll have to check the generated CSS, but in my code, none.  I only added the forms plug-in to an empty vitesse project.

**Comment by JohnCampionJr** [comment]
> @JohnCampionJr Which one comes first in your css?

I actually can't find the forms plugin CSS in the generated CSS code at all.   I'd paste it but its rather long.

**Comment by skyrpex** [comment]
I don't see any of the forms' CSS in my pages, neither.

**Comment by anncwb** [comment]
The generated css priority seems to be lower than the style tag style in SFC

**Comment by JohnCampionJr** [comment]
I don't have any styles in the SFC.  I don't see the classes at all in the generated CSS

**Comment by antfu** [comment]
As a workaround for now, you can set

```ts
// vite.config.js

WindiCSS({
  preflight: {
    enableAll: true,
  },
})
```

in v0.3.2

**Comment by JohnCampionJr** [comment]
OK, just in case it matters, this rule is still overriding the forms CSS on selects
```css
button, input, optgroup, select, textarea {
    font-family: inherit;
    font-size: 100%;
    line-height: 1.15;
    /* margin: 0; */
    /* padding: 0; */
    line-height: inherit;
    color: inherit;
}
```
