### ISSUE TITLE
CSS being generated for JS expressions and HTML tags in Vue template

### ISSUE THREAD

**Issue by ElMassimo** [windicss/vite-plugin-windicss#213]
**Describe the bug**

There seems to be a problem when parsing a Vue SFC, that causes things that are not CSS classes to be interpreted as such.

1. Using an `animate` SVG element generates the following CSS

  ```css
  .\<animate {
      -webkit-animation-iteration-count: 1;
      animation-iteration-count: 1
  }
  ```

2. Using a `duration.value` expression in CSS generates

  ```css
  .duration\.value {
      -webkit-transition-duration: 150ms;
      -o-transition-duration: 150ms;
      transition-duration: 150ms
  }
  ```

3. Interpolating a variable named `duration` in the template generates

  ```css
  .duration {
      -webkit-transition-duration: 150ms;
      -o-transition-duration: 150ms;
      transition-duration: 150ms
  }
  ```

**Minimal Reproductions**

Created a [repo with a small Vite app](https://github.com/ElMassimo/windicss-tag-repro) that replicates the mentioned bugs.

**Versions**

- vite-plugin-windicss: 1.2.5
- vite: 2.4.3
- framework: vue
