### ISSUE TITLE
Missing @layer CSS outputs in the build CSS output

### ISSUE THREAD

**Issue by upupming** [windicss/vite-plugin-windicss#260]
**Describe the bug**

Update:

Sorry to bother, I find this is not a bug but it is due to the default included pattern of WindiCSS is:

```js
extract: {
    // accepts globs and file paths relative to project root
    include: [
      'index.html',
      'src/**/*.{vue,html,jsx,tsx}',
    ],
```

But I put the CSS file in the root folder, this is not included by the default value.

However, the CSSParser has a hash bug, and I have opened an PR in the windicss repo.

<hr>

`@layer` works in dev time, but it failed to be included in build time.

```css
@layer base {
    h1 {
        color: green;
    }
}
```

**Minimal Reproductions**

See this repo: https://github.com/upupming/windicss-missig-layer-build-time

**Versions**
- vite-plugin-windicss: 1.5.4
- vite: 2.6.14
- framework(vue/react/svelte/etc): none

**Additonal Context**

There are also several additional bugs in dev time:

- the precedence (order) of layers are not handled correctly:

This expects `red` (since `components` is the last layer), but got `green` in the dev result.
```
@layer utilities {
    h1 {
        color: blue;
    }
}

@layer components {
    h1 {
        color: red;
    }
}

@layer base {
    h1 {
        color: green;
    }
}

```

- When Only use `base` layer:

```js
import 'virtual:windi-base.css'
```

The following input does not work:

```js
@layer base {
    h1 {
        color: green;
    }
}

```

But I have to add `import 'virtual:windi-components.css'` to the JS definition too, to make it works.

<hr

**Comment by upupming** [comment]
After some debuging, I find there are some bugs at the [CSSParser](https://github.com/windicss/windicss/blob/bcd50d877e62630f191602ddeabd9f677cc6d90c/src/utils/parser/css.ts#L139).

This CSS:

```css
@layer utilities {
    .h1 {
        color: blue;
    }
}

@layer base {
    .h1 {
        color: green;
    }
}
@layer components {
    .h1 {
        color: red;
    }
}
```

Will got this AST:

![image](https://user-images.githubusercontent.com/24741764/144795743-4f7d6162-e9ba-4881-acf1-043699ae1501.png)

The two `h1` should be placed in different meta types, but now all of them are recognized as `utilities` type, which is wrong, I will try my best to fix this issue.
