### ISSUE TITLE
nested @apply not working with svelte

### ISSUE THREAD

**Issue by dominikg** [windicss/vite-plugin-windicss#54]
App.svelte
```html
<style>
    h1 {
        @apply text-svelte-500 p-2 bg-green-200;
    }

    @screen sm {
        h1 {
            @apply text-blue-500;
        }
    }
</style>
```
is turned into
```css
@media (min-width: 640px) {
  @apply text-blue-500;
}
h1.svelte-10vxxvj {
  --tw-text-opacity: 1;
  color: rgba(255, 62, 0, var(--tw-text-opacity));
  padding: 0.5rem;
  --tw-bg-opacity: 1;
  background-color: rgba(167, 243, 208, var(--tw-bg-opacity));
}
```
Repro here: https://github.com/dominikg/svite-windicss

notice @svitejs/vite-plugin-svelte uses emitCss: true and a virtual css module App.svelte.css
