### ISSUE TITLE
Nesting CSS does not work in scoped Vue style blocks + line comments silently fails instead of throwing errors

### ISSUE THREAD

**Issue by ahku** [windicss/vite-plugin-windicss#96]
Example:
```html
<template>
<div class="Comp">
  <div class="Comp-child"></div>
</div>
</template>

<style>
.Comp {
  border: 1px solid red;

  &-child {
    border: 10px solid green;
  }
}
</style>
```

The green border will disappear when changing to `<style scoped>`. 

Turns out that the nesting is incorrect. The resulting CSS should look like this:

``` css
.Comp-child[data-v-16ba4180] { border: 1px solid green; }
```

But instead WindiCSS compiles it to:

```css
.Comp[data-v-16ba4180]-child[data-v-16ba4180] {
  border: 10px solid green;
}
```

**Comment by ahku** [comment]
Okay, thanks for transferring the issue. Didn't know that you could do that. I'm new to this.

The thing that makes me confused here is whether it's Windi or Vite that provides the nesting capability?

**Comment by voorjaar** [comment]
Windi provided nesting capability. We only compile css. And the scoped style is plugin's job.

**Comment by antfu** [comment]
@ahku can you try with 

```ts
WindiCSS({
  transformCSS: 'pre'
})
```

Thanks

**Comment by ahku** [comment]
@antfu That did work! Why isn't that on by default?

**Comment by ahku** [comment]
Okay, next thing then:

Is it Windy or Vite that can make this happen:

```scss
.Comp1,
.Comp2 {
  border: 1px solid red;

  &-child {
    border:10px solid green;
  }
}
```

Should compile into:

```css
.Comp1, .Comp2 { border: 1px solid red }
.Comp1-child,  .Comp2-child { border: 10px solid green }
```
